spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Sobreescribible via variable de entorno EUREKA_INSTANCE_HOSTNAME
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}

management.endpoints.web.exposure.include=health,info